### ISSUE TITLE
github: api.github.com can only be accessed via https

### ISSUE THREAD

**Issue by weisjohn** [weisjohn/kamino#3]
It seems like Github made a change:

with a `~/.kaminorc` of:

```
host=api.github.com
token=[redacted]
dir=/Users/jweis/mysrc    
```

running `kamino`, I get:

```
TypeError: Cannot read property 'body' of undefined
    at Request._callback (/Users/jweis/mysrc/weisjohn/kamino/bin/kamino:76:28)
    at self.callback (/Users/jweis/mysrc/weisjohn/kamino/node_modules/request/request.js:129:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/Users/jweis/mysrc/weisjohn/kamino/node_modules/request/request.js:239:10)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

 - [ ] if host == "api.github.com", use "https"
 - [ ] provide a more helpful error message for other errors

**Comment by weisjohn** [comment]
totally invalid, outdated version
